### ISSUE TITLE
Cool idea!

### ISSUE THREAD

**Issue by franckflo** [jsavko/swtextcrawl#1]
Would you be able to do similar text crawls in other formats? Like a computer screen filling characters little by little, or a scroll unrolling and displaying gothic text?

**Comment by jsavko** [comment]
This project was purely written in CSS which allows for easily adding other text into the animated crawl.  A typewriter animation is possible with pure CSS, but it would become problematic when adding multiple lines of text of variable lengths.  It's not impossible, but would require significantly more work adding JavaScript hooks.  If I end up running a cyberpunk game in the future I'll likely add that functionality, but at this time it's out side of the scope of the module.
