### ISSUE TITLE
Perfect Module! Just a couple of questions

### ISSUE THREAD

**Issue by Sonny-Crockett** [jsavko/swtextcrawl#2]
Can I pause(or start button) it so it gives the players time to load it up, then play it? Also a replay button for players to re-read it?

Thanks!

**Comment by BabyfaceFinlayson** [comment]
Seconded. Pause/start button would make this perfect — giving time to enlarge the crawl to the preferred size and cue music etc.

**Comment by jsavko** [comment]
This is a pure css implementation and doesn't have the ability to be paused
