### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by brunocalado** [jsavko/swtextcrawl#6]
Hi.

Please remove the foundry vtt warning.

Replace "compatibleCoreVersion":"0.9.0" by "compatibleCoreVersion":"9".

Docs: https://gitlab.com/foundrynet/foundryvtt/-/issues/5635

**Comment by jsavko** [comment]
You're welcome to make a pull request.

**Comment by brunocalado** [comment]
on my instalation I just changed one line

![image](https://user-images.githubusercontent.com/4999783/149680316-641b6b85-a7d6-4ea7-9f2e-4a32a8749fa8.png)

**Comment by jsavko** [comment]
I understand how to remove the warning.  I’m not actively developing this module and am unconcerned with the warning.   You’re welcome to make a PR though
